name: Scanner test

on:
  pull_request:

jobs:
  checkov:
    steps:
      runs-on: ubuntu-latest-medium
      name: Checkov
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Checkov
          uses: bridgecrewio/checkov-action@v12
          with:
            framework: terraform
            directory: ./aws-deploy
            output_format: cli


